# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
highlighter:      rouge
plugins:             [jekyll-paginate, rouge, jekyll-gist, jekyll-watch]

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            'Salesforce Blog'
tagline:          ' - <a href="http://xixiao.info/">@Xi Xiao</a>'
description:      Dedicated for learning Salesforce
url:              http://sf.xixiao.info
baseurl:          ""

author:
  name:           'Xi Xiao'
  url:            http://xixiao.info

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Xixiao007

post:
  template: _post.txt
  extension: md

draft:
  template: _draft.txt
  extension: md

page:
  template: _page.txt
  extension: md

# Post sharing icons
sharing:
    twitter: true
    linkedin: true
    facebook: true
    google_plus: true
    reddit: true
